version: 0.0
os: linux
files:
  - source: /
  - destinaton: /home/ec2-user/aws-node-ts-backend
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
